import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1500, height: 900 } })
const errors = []
p.on('pageerror', (e) => errors.push(String(e).slice(0, 200)))
await p.goto('http://localhost:5273', { waitUntil: 'networkidle' })
await p.click('#tile-ai')
await p.waitForTimeout(300)
await p.check('#live')
await p.waitForTimeout(4000)
const evalLine = await p.textContent('#eval-line')
const lines = await p.textContent('#lines')
const pv = await p.textContent('#pv-line')
const info = await p.textContent('#engine-info')
const mctsLines = await p.textContent('#mcts-lines')
const mctsInfo = await p.textContent('#mcts-info')
console.log('negamax eval :', evalLine?.trim())
console.log('negamax top  :', lines?.replace(/\s+/g, ' ').slice(0, 80))
console.log('PV           :', pv?.slice(0, 80))
console.log('info         :', info?.trim())
console.log('mcts         :', mctsLines?.replace(/\s+/g, ' ').slice(0, 90))
console.log('mcts info    :', mctsInfo?.trim())
console.log('erreurs      :', errors.length ? errors : 'aucune')
await b.close()
