import fs from 'node:fs'

const FILE = 'server/server.ts'
const src = fs.readFileSync(FILE, 'utf8')
const lines = src.split(/\r?\n/)

const start = lines.findIndex((l) => /^  ws\.on\('message'/.test(l))
let end = -1
for (let i = start + 1; i < lines.length; i++) {
  if (/^  \}\)$/.test(lines[i])) { end = i; break }
}
if (start < 0 || end < 0) {
  console.log('bornes introuvables', start, end)
  process.exit(1)
}

const block = [
  "  ws.on('message', (data) => {",
  '    let msg: Record<string, unknown>',
  '    try {',
  '      msg = JSON.parse(String(data))',
  '    } catch {',
  '      return',
  '    }',
  "    if (handleAuthish(msg)) return",
  "    const type = msg.type as string",
  '',
  "    if (type === 'create') {",
  "      const name = String(msg.name ?? 'Joueur').slice(0, 24)",
  '      const cfg = clockFromKey(msg.clock)',
  '      const r: Room = {',
  '        id: genCode(),',
  '        game: new Game(),',
  '        seats: [',
  '          { ws, name, account: authName ?? undefined, color: \'black\' },',
  "          { ws: null, name: '' },",
  '        ],',
  '        wantRematch: [false, false],',
  '      }',
  '      if (cfg) r.clock = { cfg, rem: [cfg.base, cfg.base], turnStart: Date.now() }',
  '      rooms.set(r.id, r)',
  '      broadcastLobby()',
  '      send(ws, {',
  "        type: 'joined',",
  '        code: r.id,',
  "        color: 'black',",
  '        state: publicState(r),',
  "        oppName: '',",
  '        myRating: publicByName(authName)?.rating ?? null,',
  '      })',
  '      return',
  '    }',
  '',
  "    if (type === 'quick') {",
  "      const name = String(msg.name ?? 'Joueur').slice(0, 24)",
  '      const idxInQueue = quickQueue.findIndex((q) => q.ws === ws)',
  '      if (idxInQueue >= 0) {',
  '        quickQueue.splice(idxInQueue, 1)',
  "        send(ws, { type: 'queue-left' })",
  '        return',
  '      }',
  '      quickQueue.push({ ws, name, account: authName ?? undefined })',
  "      send(ws, { type: 'queued', count: quickQueue.length })",
  '      while (quickQueue.length >= 2) {',
  '        const A = quickQueue.shift()!',
  '        const B = quickQueue.shift()!',
  "        const cfg = FAST ? { base: 600, inc: 0 } : CLOCKS['5+0']",
  '        const colors: Color[] =',
  "          Math.random() < 0.5 ? ['black', 'white'] : ['white', 'black']",
  '        const r: Room = {',
  '          id: genCode(),',
  '          game: new Game(),',
  '          seats: [',
  '            { ws: A.ws, name: A.name, account: A.account, color: colors[0] },',
  '            { ws: B.ws, name: B.name, account: B.account, color: colors[1] },',
  '          ],',
  '          wantRematch: [false, false],',
  "          clockKey: FAST ? 'test' : '5+0',",
  '          clock: { cfg, rem: [cfg.base, cfg.base], turnStart: Date.now() },',
  '        }',
  '        rooms.set(r.id, r)',
  '        broadcastLobby()',
  '        ;[A, B].forEach((q, i) => {',
  '          send(q.ws, {',
  "            type: 'joined',",
  '            code: r.id,',
  '            color: colors[i],',
  '            state: publicState(r),',
  '            oppName: (i === 0 ? B : A).name,',
  '            myRating: publicByName((i === 0 ? A : B).account)?.rating ?? null,',
  '            oppRating: publicByName((i === 0 ? B : A).account)?.rating ?? null,',
  '          })',
  '        })',
  "        broadcast(r, { type: 'start' })",
  '        broadcastLobby()',
  '      }',
  '      return',
  '    }',
  '',
  "    if (type === 'cancel-quick') {",
  '      const idxInQueue = quickQueue.findIndex((q) => q.ws === ws)',
  '      if (idxInQueue >= 0) quickQueue.splice(idxInQueue, 1)',
  "      send(ws, { type: 'queue-left' })",
  '      return',
  '    }',
  '',
  "    if (type === 'join') {",
  "      const code = String(msg.code ?? '').toUpperCase()",
  '      const target = rooms.get(code)',
  '      if (!target) {',
  "        send(ws, { type: 'error', message: 'Salon introuvable' })",
  '        return',
  '      }',
  '      const free = target.seats.findIndex((s) => s.ws === null)',
  '      if (free < 0) {',
  "        send(ws, { type: 'error', message: 'Salon complet' })",
  '        return',
  '      }',
  "      const name = String(msg.name ?? 'Joueur').slice(0, 24)",
  '      target.seats[free] = { ws, name, account: authName ?? undefined, color: COLORS[free] }',
  '      send(ws, {',
  "        type: 'joined',",
  '        code: target.id,',
  '        color: COLORS[free],',
  '        state: publicState(target),',
  '        oppName: target.seats[1 - free].name,',
  '        myRating: publicByName(authName)?.rating ?? null,',
  '        oppRating: publicByName(target.seats[1 - free].account)?.rating ?? null,',
  '      })',
  "      send(target.seats[1 - free].ws, { type: 'oppJoined', name })",
  "      broadcast(target, { type: 'start' })",
  '      broadcastLobby()',
  '      return',
  '    }',
  '',
  '    const loc = locate(ws)',
  '    if (!loc) {',
  "      send(ws, { type: 'error', message: 'Tu n’es dans aucun salon' })",
  '      return',
  '    }',
  '    const room = loc.room',
  '    const me = loc.me',
  '    const myColor = room.seats[me].color',
  '',
  "    if (type === 'move') {",
  '      if (room.game.winner || room.result) {',
  "        send(ws, { type: 'error', message: 'La partie est finie' })",
  '        return',
  '      }',
  '      if (room.game.position.turn !== myColor) {',
  "        send(ws, { type: 'error', message: 'Ce n’est pas ton tour' })",
  '        return',
  '      }',
  '      const now = Date.now()',
  '      if (room.clock && !FAST) {',
  '        room.clock.rem[me] -= now - room.clock.turnStart',
  '        room.clock.turnStart = now',
  '        if (room.clock.rem[me] <= 0) {',
  '          room.clock.rem[me] = 0',
  "          endRoomGame(room, other(myColor), 'temps')",
  '          return',
  '        }',
  '      }',
  '      const action = msg.action as Action',
  '      if (!room.game.play(action)) {',
  "        send(ws, { type: 'error', message: 'Coup illégal', state: publicState(room) })",
  '        return',
  '      }',
  '      if (room.clock) {',
  '        room.clock.rem[me] += room.clock.cfg.inc',
  '        room.clock.turnStart = now',
  '      }',
  '      send(opponentOf(room, me).ws, { type: \'move\', action })',
  "      send(ws, { type: 'ack', action })",
  '      broadcast(room, publicState(room))',
  '      if (room.game.winner) {',
  "        endRoomGame(room, room.game.winner, room.game.winnerReason || 'percée')",
  '      }',
  '      return',
  '    }',
  '',
  "    if (type === 'resign') {",
  '      if (room.game.winner || room.result) return',
  "      endRoomGame(room, other(myColor), 'abandon')",
  '      return',
  '    }',
  '',
  "    if (type === 'leave-room') {",
  '      const loc2 = locate(ws)',
  '      if (!loc2) return',
  '      freeSeat(loc2.room, loc2.me)',
  "      send(ws, { type: 'left-room' })",
  '      return',
  '    }',
  '',
  "    if (type === 'rematch') {",
  '      if (!room.result && !room.game.winner) return',
  '      room.wantRematch[me] = true',
  '      if (room.wantRematch[0] && room.wantRematch[1]) {',
  '        room.game = new Game()',
  '        room.result = undefined',
  '        room.wantRematch = [false, false]',
  '        if (room.clock) {',
  '          room.clock.rem = [room.clock.cfg.base, room.clock.cfg.base]',
  '          room.clock.turnStart = Date.now()',
  '        }',
  '        room.seats.forEach((s) => {',
  '          send(s.ws, {',
  "            type: 'joined',",
  '            code: room.id,',
  '            color: other(s.color),',
  '            state: publicState(room),',
  "            oppName: room.seats.find((x) => x !== s)?.name ?? '',",
  '            myRating: publicByName(s.account)?.rating ?? null,',
  '            oppRating: publicByName(room.seats.find((x) => x !== s)?.account)?.rating ?? null,',
  '          })',
  '        })',
  "        broadcast(room, { type: 'start' })",
  '        broadcastLobby()',
  '      } else {',
  "        send(ws, { type: 'rematch-wait' })",
  '      }',
  '      return',
  '    }',
  '  })',
]

lines.splice(start, end - start + 1, ...block)
fs.writeFileSync(FILE, lines.join('\n'))
console.log(`bloc remplacé : lignes ${start + 1}..${end + 1} → ${block.length} lignes`)
